"""Add server default to created_at

Revision ID: a8f3cb0a08d3
Revises: c4792046f370
Create Date: 2025-08-08 03:27:52.118740

"""
from typing import Sequence, Union
from sqlalchemy import text

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8f3cb0a08d3'
down_revision: Union[str, Sequence[str], None] = 'c4792046f370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column(
        'users',
        'created_at',
        server_default=text('now()'),
        existing_type=sa.DateTime(timezone=True),
        existing_nullable=True
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###







#разобраться с автоматической вставки created_at потом двигаться дальше